spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**,/hotelstaff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**

server:
  port: 8084
okta:
  oauth2:
    issuer: https://dev-86813575.okta.com/oauth2/default
    audience: api://default
    client-id: 0oabnrb6gorGRvSe95d7
    client-secret: 0oabnrb6gorGRvSe95d7
    scopes: openid, profile, email, offline_access
